"""Issue server/client cert signed by Root CA (SAN=DNSName(CN)).""" 
#raise NotImplementedError("students: implement cert issuance")

#!/usr/bin/env python3
"""
scripts/gen_cert.py
Generate an RSA key and a certificate signed by the Root CA generated by gen_ca.py.

Usage:
    python scripts/gen_cert.py --cn server.local --out certs/server --ca certs/ca.crt.pem --cakey certs/ca.key.pem

This creates:
    certs/server.key.pem   (private key)
    certs/server.crt.pem   (certificate signed by CA)
"""
import argparse
from datetime import datetime, timedelta, UTC
from pathlib import Path
from typing import List

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.x509.oid import NameOID


def load_ca(ca_cert_path: Path, ca_key_path: Path):
    from cryptography.hazmat.primitives.serialization import load_pem_private_key
    from cryptography.hazmat.backends import default_backend

    ca_cert = x509.load_pem_x509_certificate(ca_cert_path.read_bytes())
    ca_key = load_pem_private_key(ca_key_path.read_bytes(), password=None, backend=default_backend())
    return ca_cert, ca_key


def gen_cert(cn: str, out_prefix: Path, ca_cert_path: Path, ca_key_path: Path,
             san_dns: List[str] = None, days_valid: int = 365, key_size: int = 2048):
    out_prefix.parent.mkdir(parents=True, exist_ok=True)
    key_path = out_prefix.with_suffix('.key.pem')
    cert_path = out_prefix.with_suffix('.crt.pem')

    ca_cert, ca_key = load_ca(ca_cert_path, ca_key_path)

    # Generate entity key
    private_key = rsa.generate_private_key(public_exponent=65537, key_size=key_size)

    # Subject name
    subject = x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, cn)])

    # Build certificate
    now = datetime.now(UTC)
    builder = (
        x509.CertificateBuilder()
        .subject_name(subject)
        .issuer_name(ca_cert.subject)
        .public_key(private_key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(now - timedelta(minutes=5))
        .not_valid_after(now + timedelta(days=days_valid))
        .add_extension(x509.BasicConstraints(ca=False, path_length=None), critical=True)
        .add_extension(
            x509.KeyUsage(
                digital_signature=True,
                key_encipherment=True,
                key_cert_sign=False,
                crl_sign=False,          # ✅ Required now
                key_agreement=True,
                content_commitment=True,
                data_encipherment=False,
                encipher_only=False,
                decipher_only=False
            ),
            critical=True
        )
    )

    # SANs
    san_list = [x509.DNSName(cn)]
    if san_dns:
        for d in san_dns:
            san_list.append(x509.DNSName(d))
    builder = builder.add_extension(x509.SubjectAlternativeName(san_list), critical=False)

    # Sign certificate with CA
    cert = builder.sign(private_key=ca_key, algorithm=hashes.SHA256())

    # Write private key
    with open(key_path, "wb") as f:
        f.write(private_key.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.TraditionalOpenSSL,
            encryption_algorithm=serialization.NoEncryption()
        ))

    # Write certificate
    with open(cert_path, "wb") as f:
        f.write(cert.public_bytes(serialization.Encoding.PEM))

    print(f"Wrote key -> {key_path}")
    print(f"Wrote cert -> {cert_path}")


def main():
    p = argparse.ArgumentParser(description="Generate entity key and sign certificate with Root CA")
    p.add_argument('--cn', required=True, help="Common Name (CN) for certificate, e.g. server.local")
    p.add_argument('--out', default="certs/entity", help="Output prefix (default certs/entity)")
    p.add_argument('--ca', default="certs/ca.crt.pem", help="Path to CA certificate (PEM)")
    p.add_argument('--cakey', default="certs/ca.key.pem", help="Path to CA private key (PEM)")
    p.add_argument('--san', nargs='*', help="Additional DNS SubjectAltNames")
    p.add_argument('--days', type=int, default=365, help="Validity days (default 1 year)")
    p.add_argument('--keysize', type=int, default=2048, help="Entity RSA key size")
    args = p.parse_args()

    gen_cert(args.cn, Path(args.out), Path(args.ca), Path(args.cakey),
             san_dns=args.san, days_valid=args.days, key_size=args.keysize)


if __name__ == "__main__":
    main()
